// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: circt-opt -lower-std-to-handshake %s | FileCheck %s
  func @affine_load(%arg0: index) {
// CHECK:       module {

// CHECK-LABEL:   handshake.func @affine_load(
// CHECK-SAME:                                %[[VAL_0:.*]]: index, %[[VAL_1:.*]]: none, ...) -> none attributes {argNames = ["in0", "inCtrl"], resNames = ["outCtrl"]} {
// CHECK:           %[[VAL_2:.*]]:3 = memory(%[[VAL_3:.*]]#0, %[[VAL_3]]#1, %[[VAL_4:.*]]) {id = 1 : i32, ld_count = 1 : i32, lsq = false, st_count = 1 : i32, type = memref<10xf32>} : (f32, index, index) -> (f32, none, none)
// CHECK:           %[[VAL_5:.*]]:2 = fork(%[[VAL_2]]#2) {control = true} : (none) -> (none, none)
// CHECK:           %[[VAL_6:.*]]:2 = memory(%[[VAL_7:.*]]) {id = 0 : i32, ld_count = 1 : i32, lsq = false, st_count = 0 : i32, type = memref<10xf32>} : (index) -> (f32, none)
// CHECK:           %[[VAL_8:.*]] = merge(%[[VAL_0]]) : (index) -> index
// CHECK:           %[[VAL_9:.*]]:4 = fork(%[[VAL_1]]) {control = true} : (none) -> (none, none, none, none)
// CHECK:           %[[VAL_10:.*]] = constant(%[[VAL_9]]#2) {value = 0 : index} : (none) -> index
// CHECK:           %[[VAL_11:.*]] = constant(%[[VAL_9]]#1) {value = 10 : index} : (none) -> index
// CHECK:           %[[VAL_12:.*]] = constant(%[[VAL_9]]#0) {value = 1 : index} : (none) -> index
// CHECK:           %[[VAL_13:.*]] = branch(%[[VAL_8]]) : (index) -> index
// CHECK:           %[[VAL_14:.*]] = branch(%[[VAL_9]]#3) {control = true} : (none) -> none
// CHECK:           %[[VAL_15:.*]] = branch(%[[VAL_10]]) : (index) -> index
// CHECK:           %[[VAL_16:.*]] = branch(%[[VAL_11]]) : (index) -> index
// CHECK:           %[[VAL_17:.*]] = branch(%[[VAL_12]]) : (index) -> index
// CHECK:           %[[VAL_18:.*]] = mux(%[[VAL_19:.*]]#3, %[[VAL_20:.*]], %[[VAL_16]]) : (index, index, index) -> index
// CHECK:           %[[VAL_21:.*]]:2 = fork(%[[VAL_18]]) : (index) -> (index, index)
// CHECK:           %[[VAL_22:.*]] = mux(%[[VAL_19]]#2, %[[VAL_23:.*]], %[[VAL_13]]) : (index, index, index) -> index
// CHECK:           %[[VAL_24:.*]] = mux(%[[VAL_19]]#1, %[[VAL_25:.*]], %[[VAL_17]]) : (index, index, index) -> index
// CHECK:           %[[VAL_26:.*]]:2 = control_merge(%[[VAL_27:.*]], %[[VAL_14]]) {control = true} : (none, none) -> (none, index)
// CHECK:           %[[VAL_19]]:4 = fork(%[[VAL_26]]#1) : (index) -> (index, index, index, index)
// CHECK:           %[[VAL_28:.*]] = mux(%[[VAL_19]]#0, %[[VAL_29:.*]], %[[VAL_15]]) : (index, index, index) -> index
// CHECK:           %[[VAL_30:.*]]:2 = fork(%[[VAL_28]]) : (index) -> (index, index)
// CHECK:           %[[VAL_31:.*]] = arith.cmpi slt, %[[VAL_30]]#1, %[[VAL_21]]#1 : index
// CHECK:           %[[VAL_32:.*]]:5 = fork(%[[VAL_31]]) : (i1) -> (i1, i1, i1, i1, i1)
// CHECK:           %[[VAL_33:.*]], %[[VAL_34:.*]] = conditional_branch(%[[VAL_32]]#4, %[[VAL_21]]#0) : (i1, index) -> (index, index)
// CHECK:           sink(%[[VAL_34]]) : (index) -> ()
// CHECK:           %[[VAL_35:.*]], %[[VAL_36:.*]] = conditional_branch(%[[VAL_32]]#3, %[[VAL_22]]) : (i1, index) -> (index, index)
// CHECK:           sink(%[[VAL_36]]) : (index) -> ()
// CHECK:           %[[VAL_37:.*]], %[[VAL_38:.*]] = conditional_branch(%[[VAL_32]]#2, %[[VAL_24]]) : (i1, index) -> (index, index)
// CHECK:           sink(%[[VAL_38]]) : (index) -> ()
// CHECK:           %[[VAL_39:.*]], %[[VAL_40:.*]] = conditional_branch(%[[VAL_32]]#1, %[[VAL_26]]#0) {control = true} : (i1, none) -> (none, none)
// CHECK:           %[[VAL_41:.*]], %[[VAL_42:.*]] = conditional_branch(%[[VAL_32]]#0, %[[VAL_30]]#0) : (i1, index) -> (index, index)
// CHECK:           sink(%[[VAL_42]]) : (index) -> ()
// CHECK:           %[[VAL_43:.*]] = merge(%[[VAL_41]]) : (index) -> index
// CHECK:           %[[VAL_44:.*]]:2 = fork(%[[VAL_43]]) : (index) -> (index, index)
// CHECK:           %[[VAL_45:.*]] = merge(%[[VAL_35]]) : (index) -> index
// CHECK:           %[[VAL_46:.*]]:2 = fork(%[[VAL_45]]) : (index) -> (index, index)
// CHECK:           %[[VAL_47:.*]] = merge(%[[VAL_37]]) : (index) -> index
// CHECK:           %[[VAL_48:.*]]:2 = fork(%[[VAL_47]]) : (index) -> (index, index)
// CHECK:           %[[VAL_49:.*]] = merge(%[[VAL_33]]) : (index) -> index
// CHECK:           %[[VAL_50:.*]]:2 = control_merge(%[[VAL_39]]) {control = true} : (none) -> (none, index)
// CHECK:           %[[VAL_51:.*]]:4 = fork(%[[VAL_50]]#0) {control = true} : (none) -> (none, none, none, none)
// CHECK:           %[[VAL_52:.*]]:2 = fork(%[[VAL_51]]#3) {control = true} : (none) -> (none, none)
// CHECK:           %[[VAL_53:.*]] = join(%[[VAL_52]]#1, %[[VAL_6]]#1, %[[VAL_5]]#1, %[[VAL_2]]#1) {control = true} : (none, none, none, none) -> none
// CHECK:           sink(%[[VAL_50]]#1) : (index) -> ()
// CHECK:           %[[VAL_54:.*]] = arith.addi %[[VAL_44]]#1, %[[VAL_46]]#1 : index
// CHECK:           %[[VAL_55:.*]] = constant(%[[VAL_52]]#0) {value = 7 : index} : (none) -> index
// CHECK:           %[[VAL_56:.*]] = arith.addi %[[VAL_54]], %[[VAL_55]] : index
// CHECK:           %[[VAL_57:.*]]:3 = fork(%[[VAL_56]]) : (index) -> (index, index, index)
// CHECK:           %[[VAL_58:.*]], %[[VAL_7]] = load(%[[VAL_57]]#2, %[[VAL_6]]#0, %[[VAL_51]]#2) : (index, f32, none) -> (f32, index)
// CHECK:           %[[VAL_59:.*]] = arith.addi %[[VAL_44]]#0, %[[VAL_48]]#1 : index
// CHECK:           %[[VAL_60:.*]], %[[VAL_4]] = load(%[[VAL_57]]#1, %[[VAL_2]]#0, %[[VAL_51]]#1) : (index, f32, none) -> (f32, index)
// CHECK:           %[[VAL_61:.*]] = arith.addf %[[VAL_58]], %[[VAL_60]] : f32
// CHECK:           %[[VAL_62:.*]] = join(%[[VAL_51]]#0, %[[VAL_5]]#0) {control = true} : (none, none) -> none
// CHECK:           %[[VAL_3]]:2 = store(%[[VAL_61]], %[[VAL_57]]#0, %[[VAL_62]]) : (f32, index, none) -> (f32, index)
// CHECK:           %[[VAL_23]] = branch(%[[VAL_46]]#0) : (index) -> index
// CHECK:           %[[VAL_25]] = branch(%[[VAL_48]]#0) : (index) -> index
// CHECK:           %[[VAL_20]] = branch(%[[VAL_49]]) : (index) -> index
// CHECK:           %[[VAL_27]] = branch(%[[VAL_53]]) {control = true} : (none) -> none
// CHECK:           %[[VAL_29]] = branch(%[[VAL_59]]) : (index) -> index
// CHECK:           %[[VAL_63:.*]]:2 = control_merge(%[[VAL_40]]) {control = true} : (none) -> (none, index)
// CHECK:           sink(%[[VAL_63]]#1) : (index) -> ()
// CHECK:           return %[[VAL_63]]#0 : none
// CHECK:         }
// CHECK:       }


    %0 = memref.alloc() : memref<10xf32>
    %10 = memref.alloc() : memref<10xf32>
    %c0 = arith.constant 0 : index
    %c10 = arith.constant 10 : index
    %c1 = arith.constant 1 : index
    br ^bb1(%c0 : index)
  ^bb1(%1: index):      // 2 preds: ^bb0, ^bb2
    %2 = arith.cmpi slt, %1, %c10 : index
    cond_br %2, ^bb2, ^bb3
  ^bb2: // pred: ^bb1
    %3 = arith.addi %1, %arg0 : index
    %c7 = arith.constant 7 : index
    %4 = arith.addi %3, %c7 : index
    %5 = memref.load %0[%4] : memref<10xf32>
    %6 = arith.addi %1, %c1 : index
    %7 = memref.load %10[%4] : memref<10xf32>
    %8 = arith.addf %5, %7 : f32
    memref.store %8, %10[%4] : memref<10xf32>
    br ^bb1(%6 : index)
  ^bb3: // pred: ^bb1
    return
  }
